# .readthedocs.yml
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - pip install poetry
    post_install:
      # Install dependencies with 'docs' dependency group
      # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
      # VIRTUAL_ENV needs to be set manually for now, see #11150
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --no-root

# Tell RTD to use the Sphinx config in docs/source/
sphinx:
  configuration: docs/source/conf.py

# If you need extra system packages (like libxml2, pandoc, etc), uncomment below:
# apt_packages:
#   - libxml2-dev
#   - pandoc

# (Optional) Set build.environment variables if needed (for data science, some need this)
# environment:
#   # Uncomment and edit as needed, e.g.:
#   # MPLBACKEND: "Agg"
